<?php

return [
    "settings" => [
        "request_timeout" => "5",
        "request_user_agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
        "report_limit_image_formats" => "AVIF,WebP",
        "report_limit_deprecated_html_tags" => "acronym,applet,basefont,big,center,dir,font,frame,frameset,isindex,noframes,s,strike,tt,u",
        "report_limit_page_size" => "330000",
        "report_limit_min_title" => "1",
        "report_limit_max_title" => "60",
        "report_limit_max_links" => "150",
        "report_limit_load_time" => "2",
        "report_limit_http_requests" => "50",
        "report_limit_max_dom_nodes" => "1500",
        "report_limit_min_words" => "500",
        "report_limit_min_text_ratio" => "10",
        "report_score_high" => "10",
        "report_score_medium" => "5",
        "report_score_low" => "0",
        "request_proxy" => NULL,
        "captcha_secret_key" => NULL,
        "captcha_site_key" => NULL,
        "locale" => "en",
        "title" => "WebaSEO"
    ],

    "report_failed_errors" => [
        "title" => "The title tag must be between 1 and 60 characters long.",
        "meta_description" => "The meta description tag is missing or empty.",
        "headings" => "Only one h1 tag should be present on the webpage.",
        "content_keywords" => "No relevant keywords found on the webpage.",
        "image_keywords" => "There are images with missing alt attributes.",
        "seo_friendly_url" => "The URL does not contain any relevant keywords.",
        "404_page" => "The website does not have 404 error pages.",
        "robots" => "The webpage cannot be accessed by search engines.",
        "noindex" => "The webpage has a noindex tag set.",
        "in_page_links" => "The number of links on the webpage is not ideal.",
        "language" => "The webpage does not have a language declared.",
        "favicon" => "The webpage does not have a favicon.",
        "text_compression" => "The HTML file is not compressed.",
        "load_time" => "The webpage has a high load time.",
        "page_size" => "The webpage HTML size is large.",
        "http_requests" => "The webpage makes more than 50 HTTP requests.",
        "image_format" => "There are images that are not using the AVIF, WebP format.",
        "defer_javascript" => "There are javascript resources without the defer attribute.",
        "dom_size" => "The DOM size is not optimal.",
        "https_encryption" => "The webpage does not use HTTPS encryption.",
        "mixed_content" => "There are mixed content resources on the webpage.",
        "server_signature" => "The webpage has a public server signature.",
        "unsafe_cross_origin_links" => "The webpage has 15 unsafe cross-origin links.",
        "plaintext_email" => "The webpage contains plaintext emails.",
        "structured_data" => "There are no structured data tags on the webpage.",
        "meta_viewport" => "The meta viewport tag is missing or is empty.",
        "charset" => "The webpage does not have a charset declared.",
        "sitemap" => "No sitemaps found.",
        "social" => "The webpage does not contain any social links.",
        "content_length" => "There are less than 500 words on the webpage.",
        "text_html_ratio" => "The text to HTML ratio is under 10%.",
        "inline_css" => "The webpage contains inline CSS code.",
        "deprecated_html_tags" => "The webpage has deprecated HTML tags."
    ]
];